AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  A prototype sam node app

Parameters:
  EnvCode:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Enter environment dev or prod
  StackPrefix:
    Type: String
    Default: sam-node-proto
    Description: Enter the stack prefix

Globals:
  Function:
    Timeout: 60

Resources:
  GreeterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        !Join ["-", [Ref: StackPrefix, GreeterFunction, Ref: EnvCode]]
      Description: "Returns a greeting message"
      CodeUri: lambdas/greeter/
      Handler: app.handler
      Role: !GetAtt LambdaRole.Arn
      Layers:
        - !Ref LibLayer
        - !Ref CodeLayer
      Runtime: nodejs12.x

  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lib
      Description: common libraries (used by the code layer or λs)
      ContentUri: layers/lib/
      CompatibleRuntimes:
        - nodejs12.x

  CodeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: code
      Description: common code that λs can share
      ContentUri: layers/code/
      CompatibleRuntimes:
        - nodejs12.x

  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: lambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
